// Generated by reactiveweb-generate. Edit the schema and regenerate.
import { ReactiveObject, ToProperty, ReactiveCommand, ReactivePropertyValidationError } from "@wieslawsoltes/reactiveweb";
import { canIncrement, doubleCount, increment } from "./counter-logic.js";

export class CounterViewModel extends ReactiveObject {
  #generatedResources: { Dispose(): void }[] = [];
  #generatedDisposed = false;
  declare readonly Double: number;
  readonly Increment: ReactiveCommand<void, number>;

  constructor(initial: Partial<Pick<CounterViewModel, "Name" | "Count">> = {}) {
    super();
    const allowedProperties = new Set(["Name","Count"]);
    for (const name of Object.keys(initial)) {
      if (!allowedProperties.has(name)) throw new TypeError(`Unknown reactive property: ${name}`);
    }
    try {
      this.Name = Object.hasOwn(initial, "Name") ? initial.Name! : "Generated counter";
      this.Count = Object.hasOwn(initial, "Count") ? initial.Count! : 0;
      this.#generatedResources.push(ToProperty(doubleCount(this), this, "Double", { initialValue: 0, deferSubscription: false }));
      this.Increment = ReactiveCommand.Create<void, number>((input: void) => increment(this, input), canIncrement(this));
      this.#generatedResources.push(this.Increment);
    } catch (error) {
      this.Dispose();
      throw error;
    }
  }

  get Name(): string { return this.GetValue<string>("Name"); }
  set Name(value: string) {
    const candidate: unknown = value;
    const valid0 = (typeof candidate === "string");
    const valid1 = (candidate !== null && candidate !== undefined && candidate !== "");
    const valid2 = ((typeof candidate === "string" || Array.isArray(candidate)) && candidate.length <= 80);
    if (!(valid0 && valid1 && valid2)) throw new ReactivePropertyValidationError("Name", value);
    if (Object.is(this.GetValue("Name"), value)) return;
    this.RaiseAndSetIfChanged("Name", value);
  }

  get Count(): number { return this.GetValue<number>("Count"); }
  set Count(value: number) {
    const candidate: unknown = value;
    const valid0 = (typeof candidate === "number" && Number.isFinite(candidate));
    const valid1 = (typeof candidate === "number" && candidate >= 0);
    const valid2 = (typeof candidate === "number" && candidate <= 1000);
    if (!(valid0 && valid1 && valid2)) throw new ReactivePropertyValidationError("Count", value);
    if (Object.is(this.GetValue("Count"), value)) return;
    this.RaiseAndSetIfChanged("Count", value);
  }

  override Dispose(): void {
    if (this.#generatedDisposed) return;
    this.#generatedDisposed = true;
    const errors: unknown[] = [];
    for (const resource of this.#generatedResources.splice(0).reverse()) {
      try { resource.Dispose(); } catch (error) { errors.push(error); }
    }
    super.Dispose();
    if (errors.length) throw new AggregateError(errors, "Generated view model disposal failed.");
  }
}
